// Catalogue centralisé des produits CargoLink Africa
// Ce fichier est la source de vérité partagée entre /catalog, /product/[id], et la homepage

export interface Product {
  id: string;
  title: string;
  subtitle: string;
  price: number; // prix unitaire FCFA
  oldPrice?: number;
  minQty: number;
  maxQty?: number;
  image: string;
  images: string[];
  category: string;
  badge?: string;
  origin: string;
  weight: string; // ex: "0.35 kg"
  volume: string; // ex: "0.002 CBM"
  rating: number;
  reviewsCount: number;
  description: string;
  features: string[];
  specifications: { label: string; value: string }[];
  reviews: { author: string; rating: number; comment: string; date: string }[];
  related: string[]; // IDs of related products
  // Étiquettes & spécifications téléphone (Catalogue FenouShop)
  conditionState?: "Scellé" | "Reconditionné" | "Occasion";
  grade?: string;
  simType?: string;
  regionVersion?: string;
  storageOptions?: string[];
  batteryHealth?: string;
}

export const PRODUCTS: Product[] = [
  // --- CATALOGUE RÉEL IPHONE FENOUSHOP ---
  {
    id: "iphone-7-7plus",
    title: "iPhone 7 & 7 Plus Grossiste (Catalogue FenouShop)",
    subtitle: "Modèles 4.7\" et 5.5\" — État certifié FenouShop",
    price: 26000,
    oldPrice: 35000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "PRIX MINIMAL",
    origin: "Chine (FenouShop Partner)",
    weight: "0.14 kg",
    volume: "0.001 CBM",
    rating: 4.6,
    reviewsCount: 142,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["32 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "Lot grossiste d'iPhone 7 et 7 Plus authentiques issus du catalogue FenouShop. Écran Retina HD, processeur A10 Fusion, appareil photo 12 MP et étanchéité IP67. Chaque téléphone subit un contrôle qualité rigoureux (batterie, écran, haut-parleur). Fourchette tarifaire de 26 000 à 72 000 FCFA selon la capacité et le grade.",
    features: [
      "Écran Retina HD 4.7\" / 5.5\"",
      "Puce A10 Fusion performante",
      "Capteur photo 12 MP 4K",
      "Touch ID empreinte digitale",
      "Batterie contrôlée (85% à 100%)",
      "Contrôle qualité FenouShop inclus",
    ],
    specifications: [
      { label: "Marque / Modèle", value: "Apple iPhone 7 & 7 Plus" },
      { label: "État / Condition", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Stockage dispo.", value: "32 Go / 128 Go / 256 Go" },
      { label: "Type SIM", value: "SIM physique" },
      { label: "État Batterie", value: "85% - 100%" },
      { label: "Plage tarifaire", value: "26 000 à 72 000 FCFA" },
      { label: "Garantie", value: "Contrôle avant expédition" },
    ],
    reviews: [
      { author: "Koffi A.", rating: 5, comment: "Reçu en parfait état de fonctionnement à Cotonou. Vendu très rapidement !", date: "12 Fév. 2025" },
    ],
    related: ["iphone-8-8plus", "iphone-x-xr-xsmax", "1"],
  },
  {
    id: "iphone-8-8plus",
    title: "iPhone 8 & 8 Plus Grossiste (Catalogue FenouShop)",
    subtitle: "Dos en verre, Puce A11 Bionic & Charge sans fil",
    price: 33000,
    oldPrice: 45000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    origin: "Chine (FenouShop Partner)",
    weight: "0.15 kg",
    volume: "0.001 CBM",
    rating: 4.7,
    reviewsCount: 198,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["32 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "Gamme iPhone 8 et 8 Plus direct usine via FenouShop. Design élégant en verre résistant, compatibilité avec la recharge sans fil Qi et processeur A11 Bionic avec Neural Engine. Fourchette tarifaire de 33 000 à 85 000 FCFA selon la version.",
    features: [
      "Dos en verre avec recharge sans fil Qi",
      "Puce A11 Bionic haute rapidité",
      "Écran True Tone Retina HD",
      "Capteur photo 12 MP (Portraits sur 8 Plus)",
      "Vérification batterie & boutons OK",
    ],
    specifications: [
      { label: "Marque / Modèle", value: "Apple iPhone 8 & 8 Plus" },
      { label: "État", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Stockage", value: "32 Go / 128 Go / 256 Go" },
      { label: "SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "33 000 à 85 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-7-7plus", "iphone-x-xr-xsmax", "iphone-11-11pro-11promax"],
  },
  {
    id: "iphone-x-xr-xsmax",
    title: "iPhone X / XR / XS Max Grossiste",
    subtitle: "Écran Super Retina OLED & Face ID sécurisé",
    price: 46000,
    oldPrice: 65000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "POPULAIRE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.17 kg",
    volume: "0.001 CBM",
    rating: 4.8,
    reviewsCount: 310,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "La génération borderless d'Apple : iPhone X, iPhone XR et iPhone XS Max. Écran OLED Super Retina / Liquid Retina HD, déverrouillage Face ID 3D et puce A12 Bionic. Tarifs de 46 000 à 125 000 FCFA selon la configuration.",
    features: [
      "Écran panoramique borderless OLED / Liquid Retina",
      "Face ID ultra rapide et sécurisé",
      "Puce A12 Bionic Neural Engine",
      "Double appareil photo 12 MP (X & XS Max)",
      "Autonomie batterie longue durée (XR)",
    ],
    specifications: [
      { label: "Modèles", value: "iPhone X, XR, XS Max" },
      { label: "État", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Capacités", value: "64 Go / 128 Go / 256 Go" },
      { label: "Type SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "46 000 à 125 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-8-8plus", "iphone-11-11pro-11promax", "iphone-12-12pro-12promax"],
  },
  {
    id: "iphone-11-11pro-11promax",
    title: "iPhone 11 / 11 Pro / 11 Pro Max Grossiste",
    subtitle: "Triple appareil photo 4K, Mode Nuit & A13 Bionic",
    price: 79000,
    oldPrice: 110000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "BEST SELLER",
    origin: "Chine (FenouShop Partner)",
    weight: "0.19 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 520,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "256 Go"],
    batteryHealth: "88% - 100%",
    description:
      "Incontournable pour la revente : iPhone 11, 11 Pro et 11 Pro Max reconditionnés. Double ou triple capteur ultra grand-angle, vidéo 4K à 60 ips, autonomie record et verre dépoli ultra résistant. Prix grossiste de 79 000 à 198 000 FCFA.",
    features: [
      "Double / Triple capteur photo 12 MP avec Mode Nuit",
      "Puce A13 Bionic surpuissante",
      "Batterie longue autonomie",
      "Finition verre mat / acier inoxydable (Pro)",
      "Reconditionné certifié FenouShop",
    ],
    specifications: [
      { label: "Série", value: "iPhone 11 / 11 Pro / 11 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Stockages", value: "64 Go / 256 Go" },
      { label: "SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "79 000 à 198 000 FCFA" },
    ],
    reviews: [
      { author: "Saliou M.", rating: 5, comment: "Superbe lot d'iPhone 11 Pro. Qualité d'écran et batterie parfaites !", date: "02 Mar. 2025" },
    ],
    related: ["iphone-x-xr-xsmax", "iphone-12-12pro-12promax", "iphone-13-13pro-13promax"],
  },
  {
    id: "iphone-12-12pro-12promax",
    title: "iPhone 12 / 12 Pro / 12 Pro Max Grossiste",
    subtitle: "Design Ceramic Shield, Réseau 5G & MagSafe",
    price: 98000,
    oldPrice: 135000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "TENDANCE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.18 kg",
    volume: "0.001 CBM",
    rating: 4.8,
    reviewsCount: 412,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "128 Go", "256 Go"],
    batteryHealth: "88% - 100%",
    description:
      "La révolution 5G avec l'iPhone 12, 12 Pro et 12 Pro Max. Écran Super Retina XDR OLED, façade Ceramic Shield 4x plus résistante aux chutes, scanner LiDAR sur les séries Pro et recharge MagSafe. Tarifs grossistes de 98 000 à 249 000 FCFA.",
    features: [
      "Connexion ultra rapide 5G",
      "Ceramic Shield & bords plats aluminium/acier",
      "Recharge magnétique MagSafe",
      "Scanner LiDAR pour portraits de nuit (Pro)",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 12, 12 Pro, 12 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Capacités", value: "64 Go / 128 Go / 256 Go" },
      { label: "Plage tarifaire", value: "98 000 à 249 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-11-11pro-11promax", "iphone-13-13pro-13promax", "iphone-14-14pro-14promax"],
  },
  {
    id: "iphone-13-13pro-13promax",
    title: "iPhone 13 / 13 Pro / 13 Pro Max Grossiste",
    subtitle: "Puce A15 Bionic, Écran ProMotion 120Hz & Mode Cinéma",
    price: 131000,
    oldPrice: 180000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "TOP VENTES",
    origin: "Chine (FenouShop Partner)",
    weight: "0.20 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 380,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "90% - 100%",
    description:
      "Excellence technologique : iPhone 13, 13 Pro et 13 Pro Max. Encoche réduite de 20%, écran fluide ProMotion 120 Hz, Mode Cinéma pour des vidéos professionnelles avec faible profondeur de champ. Tarifs de 131 000 à 328 000 FCFA.",
    features: [
      "ProMotion 120 Hz adaptatif (13 Pro & Pro Max)",
      "Mode Cinéma automatique avec focus dynamique",
      "Puce A15 Bionic 6-cœurs",
      "Capacité jusqu'à 1 To",
      "Prise en charge eSIM + Dual SIM",
    ],
    specifications: [
      { label: "Série", value: "iPhone 13, 13 Pro, 13 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Type SIM", value: "eSIM / Dual SIM" },
      { label: "Version", value: "Version US (LL/A) / Global" },
      { label: "Plage tarifaire", value: "131 000 à 328 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-12-12pro-12promax", "iphone-14-14pro-14promax", "iphone-15-15pro-15promax"],
  },
  {
    id: "iphone-14-14pro-14promax",
    title: "iPhone 14 / 14 Pro / 14 Pro Max Grossiste",
    subtitle: "Dynamic Island, Capteur 48 MP & Détection d'Accident",
    price: 197000,
    oldPrice: 260000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "BEST SELLER",
    origin: "Chine (FenouShop Partner)",
    weight: "0.21 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 290,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "90% - 100%",
    description:
      "La gamme iPhone 14 avec l'innovation Dynamic Island sur les Pro. Capteur principal 48 MP ProRAW, écran Toujours Activé (Always-On), puce A16 Bionic et détection des accidents de la route. Fourchette tarifaire de 197 000 à 394 000 FCFA.",
    features: [
      "Dynamic Island interactive (Pro & Pro Max)",
      "Capteur photo professionnel 48 MP",
      "Puce A16 Bionic (Pro)",
      "Détection d'accident et SOS urgence",
      "Disponibilité immédiate FenouShop",
    ],
    specifications: [
      { label: "Modèles", value: "iPhone 14, 14 Plus, 14 Pro, 14 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Compatibilité SIM", value: "eSIM & Dual SIM" },
      { label: "Région", value: "Version US (LL/A)" },
      { label: "Plage tarifaire", value: "197 000 à 394 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-13-13pro-13promax", "iphone-15-15pro-15promax", "iphone-16-16pro-16promax"],
  },
  {
    id: "iphone-15-15pro-15promax",
    title: "iPhone 15 / 15 Pro / 15 Pro Max Grossiste",
    subtitle: "Châssis Titane de qualité spatiale & USB-C Universel",
    price: 230000,
    oldPrice: 310000,
    minQty: 1,
    image: "/images/assets/hero_iphone.png",
    images: ["/images/assets/hero_iphone.png", "/images/assets/card_hero_iphone.jpg"],
    category: "electronics",
    badge: "PREMIUM",
    origin: "Chine (FenouShop Partner)",
    weight: "0.19 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 215,
    conditionState: "Scellé",
    grade: "Grade A/B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US / EU",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "100% Scellé / Neuf",
    description:
      "La génération iPhone 15 en version Scellée / Neuf ou Grade A. Conçu en titane ultra léger et résistant, port USB-C 3.0 ultra rapide, bouton Action personnalisable et zoom optique 5x (Pro Max). Tarifs grossistes de 230 000 à 492 000 FCFA.",
    features: [
      "Design Titane ultra léger et robuste",
      "Connectique universelle USB-C",
      "Bouton Action programmable",
      "Puce A17 Pro gravée en 3nm",
      "Zoom optique 5x télescopique (Pro Max)",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 15, 15 Plus, 15 Pro, 15 Pro Max" },
      { label: "État produit", value: "Scellé / Neuf & Grade A/B/C" },
      { label: "Connecteur", value: "USB-C" },
      { label: "SIM", value: "eSIM / Dual SIM physique" },
      { label: "Plage tarifaire", value: "230 000 à 492 000 FCFA" },
    ],
    reviews: [
      { author: "Rodrigue T.", rating: 5, comment: "Reçu l'iPhone 15 Pro Max scellé en boîte d'origine. Produit 100% authentique !", date: "15 Jan. 2025" },
    ],
    related: ["iphone-14-14pro-14promax", "iphone-16-16pro-16promax", "iphone-17-17pro-17promax"],
  },
  {
    id: "iphone-16-16pro-16promax",
    title: "iPhone 16 / 16 Pro / 16 Pro Max Grossiste",
    subtitle: "Apple Intelligence & Nouveau Bouton Commande de l'Appareil Photo",
    price: 295000,
    oldPrice: 380000,
    minQty: 1,
    image: "/images/assets/hero_iphone16.png",
    images: ["/images/assets/hero_iphone16.png", "/images/assets/hero_iphone.png"],
    category: "electronics",
    badge: "NOUVEAU",
    origin: "Chine (FenouShop Partner)",
    weight: "0.20 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 165,
    conditionState: "Scellé",
    grade: "Grade A",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "100% Neuf d'origine",
    description:
      "Dernier né d'Apple : l'iPhone 16, 16 Pro et 16 Pro Max. Intégration d'Apple Intelligence, nouveau bouton de contrôle tactile pour la caméra, puce A18 / A18 Pro et enregistrement vidéo 4K 120 ips Dolby Vision. Prix de 295 000 à 623 000 FCFA.",
    features: [
      "Bouton haptique Commande de la Caméra",
      "Puce A18 Pro optimisée IA",
      "Écrans agrandis 6.3\" et 6.9\" (Pro)",
      "Vidéo 4K 120 ips Dolby Vision",
      "Produits 100% Scellés avec boite scellée",
    ],
    specifications: [
      { label: "Série", value: "iPhone 16, 16 Plus, 16 Pro, 16 Pro Max" },
      { label: "État", value: "Scellé / Neuf (Grade A Premium)" },
      { label: "Puce", value: "Apple A18 & A18 Pro" },
      { label: "Plage tarifaire", value: "295 000 à 623 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-15-15pro-15promax", "iphone-17-17pro-17promax"],
  },
  {
    id: "iphone-17-17pro-17promax",
    title: "iPhone 17 / 17 Pro / 17 Pro Max (Avant-Première)",
    subtitle: "Nouvelle Génération Apple A19 Pro & Refroidissement Chambre à Vapeur",
    price: 394000,
    oldPrice: 520000,
    minQty: 1,
    image: "/images/assets/hero_iphone16.png",
    images: ["/images/assets/hero_iphone16.png"],
    category: "electronics",
    badge: "AVANT-PREMIÈRE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.21 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 42,
    conditionState: "Scellé",
    grade: "Grade A",
    simType: "Dual SIM",
    regionVersion: "Version Global",
    storageOptions: ["256 Go", "512 Go", "1 To", "2 To"],
    batteryHealth: "100% Neuf d'origine",
    description:
      "La future référence d'Apple proposée en réservation grossiste par FenouShop. Puce A19 Pro, jusqu'à 2 To de stockage, système thermique à chambre à vapeur et capteurs ultra avancés. Tarifs indicatifs de 394 000 à 886 000 FCFA.",
    features: [
      "Puce A19 Pro nouvelle génération",
      "Système thermique avancé par chambre à vapeur",
      "Stockage étendu jusqu'à 2 To",
      "Design avant-gardiste ultra fin",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 17, 17 Pro, 17 Pro Max" },
      { label: "État", value: "Scellé / Neuf d'origine" },
      { label: "Stockage max.", value: "Jusqu'à 2 To" },
      { label: "Plage tarifaire", value: "394 000 à 886 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-16-16pro-16promax"],
  },
  // --- AUTRES PRODUITS EN GROS ---

  {
    id: "1",
    title: "Montre Connectée SmartFit Pro X GPS",
    subtitle: "Smartwatch haute performance — Direct Usine Certifiée",
    price: 3500,
    oldPrice: 5500,
    minQty: 5,
    maxQty: 1000,
    image: "/images/assets/item_1.jpg",
    images: ["/images/assets/item_1.jpg", "/images/assets/item_2.jpg", "/images/assets/item_3.jpg"],
    category: "electronics",
    badge: "BEST SELLER",
    origin: "Hub Asie & International",
    weight: "0.35 kg",
    volume: "0.002 CBM",
    rating: 4.7,
    reviewsCount: 248,
    description:
      "La SmartFit Pro X GPS est une montre connectée de niveau premium, produite directement en usine certifiée et disponible en lot grossiste à prix usine via FENOUHIMIN. Écran AMOLED HD 1.85\", suivi cardiaque en temps réel, SpO2, GPS intégré, étanchéité IP68 et autonomie de 7 jours. Compatible iOS & Android. Emballage individuel renforcé inclus.",
    features: [
      "Écran AMOLED 1.85\" HD",
      "GPS intégré multipoints",
      "Suivi cardiaque + SpO2 24h/24",
      "Étanchéité IP68 (30m / 30min)",
      "Autonomie 7 jours",
      "Charge magnétique rapide",
      "Compatible iOS & Android",
      "Emballage individuel inclus",
    ],
    specifications: [
      { label: "Écran", value: "AMOLED 1.85\" — 240×286px" },
      { label: "Processeur", value: "Realtek RTL8762D" },
      { label: "Mémoire", value: "512KB RAM / 4MB Flash" },
      { label: "Connectivité", value: "Bluetooth 5.0 + GPS" },
      { label: "Batterie", value: "230 mAh Li-Po" },
      { label: "Autonomie", value: "7 jours usage normal" },
      { label: "Étanchéité", value: "IP68 (30m / 30 min)" },
      { label: "Compatibilité", value: "iOS 10+ / Android 5+" },
      { label: "Poids", value: "35g avec bracelet" },
      { label: "Coloris dispo.", value: "Noir, Argent, Or Rose" },
      { label: "Minimum commande", value: "5 unités" },
      { label: "Délai production", value: "7–12 jours ouvrés" },
    ],
    reviews: [
      { author: "Abdoulaye D.", rating: 5, comment: "Parfait pour la revente au marché. Qualité bien supérieure au prix. La montre tient vraiment 7 jours.", date: "15 Jan. 2025" },
      { author: "Aicha K.", rating: 4, comment: "Livraison rapide depuis Cotonou, produit conforme aux photos. Je recommande FENOUHIMIN !", date: "03 Mar. 2025" },
      { author: "Mamadou S.", rating: 5, comment: "Commande de 50 unités, zéro casse, emballage solide. Clientèle très satisfaite.", date: "22 Avr. 2025" },
    ],
    related: ["2", "3", "7"],
  },
  {
    id: "2",
    title: "Écouteurs Bluetooth ANC SoundBass Pro",
    subtitle: "TWS Active Noise Cancelling — Lot grossiste usine",
    price: 2200,
    oldPrice: 4000,
    minQty: 5,
    image: "/images/assets/item_2.jpg",
    images: ["/images/assets/item_2.jpg", "/images/assets/item_3.jpg", "/images/assets/item_1.jpg"],
    category: "electronics",
    badge: "PROMO",
    origin: "Hub Asie & International",
    weight: "0.08 kg",
    volume: "0.001 CBM",
    rating: 4.5,
    reviewsCount: 183,
    description:
      "Écouteurs intra-auriculaires True Wireless avec réduction de bruit active (ANC). Réduction de 35dB, bass boostée, autonomie de 6h + 24h avec boîtier de charge, latence jeu ultra-faible 50ms. Idéal pour revendeurs et boutiques d'électronique.",
    features: [
      "ANC — Réduction bruit active 35dB",
      "Autonomie 6h + 24h boîtier",
      "Latence gaming 50ms",
      "Bass boostée EQ premium",
      "Certification IPX5",
      "Charge USB-C",
      "3 tailles d'embouts silicone",
    ],
    specifications: [
      { label: "Connectivité", value: "Bluetooth 5.3" },
      { label: "ANC", value: "–35 dB actif" },
      { label: "Autonomie écouteur", value: "6 heures" },
      { label: "Autonomie boîtier", value: "+24 heures" },
      { label: "Charge", value: "USB-C — 60 min" },
      { label: "Étanchéité", value: "IPX5" },
      { label: "Latence", value: "50ms mode jeu" },
      { label: "Minimum commande", value: "5 unités" },
    ],
    reviews: [
      { author: "Fatou N.", rating: 5, comment: "Excellent rapport qualité-prix pour la revente. Les clients adorent la qualité audio.", date: "10 Fév. 2025" },
    ],
    related: ["1", "3", "2"],
  },
  {
    id: "3",
    title: "Casque Audio Over-Ear Wireless Hi-Fi",
    subtitle: "Casque supra-auriculaire premium — Direct Usine",
    price: 4500,
    oldPrice: 7000,
    minQty: 5,
    image: "/images/assets/item_3.jpg",
    images: ["/images/assets/item_3.jpg", "/images/assets/item_2.jpg", "/images/assets/item_1.jpg"],
    category: "electronics",
    origin: "Hub International Usines",
    weight: "0.28 kg",
    volume: "0.003 CBM",
    rating: 4.6,
    reviewsCount: 156,
    description: "Casque over-ear sans fil avec drivers 40mm, basses profondes, réduction bruit passive, coussinets mémoire de forme en similicuir premium. Autonomie 35h. Pliable pour transport.",
    features: ["Drivers 40mm haute résolution", "Autonomie 35h", "Pliable compact", "Coussinets mémoire de forme", "Charge USB-C"],
    specifications: [
      { label: "Drivers", value: "40mm HD" },
      { label: "Autonomie", value: "35 heures" },
      { label: "Charge", value: "USB-C 90 min" },
      { label: "Minimum commande", value: "5 unités" },
    ],
    reviews: [],
    related: ["1", "2"],
  },
  {
    id: "4",
    title: "Baskets Urban High-Top Sneaker Pro",
    subtitle: "Chaussures de sport urbaines — Collection 2025",
    price: 2800,
    oldPrice: 4500,
    minQty: 5,
    image: "/images/assets/item_4.jpg",
    images: ["/images/assets/item_4.jpg", "/images/assets/item_6.jpg", "/images/assets/item_8.jpg"],
    category: "fashion",
    origin: "Hub International Usines",
    weight: "0.55 kg",
    volume: "0.005 CBM",
    rating: 4.4,
    reviewsCount: 312,
    description: "Sneakers haute tige streetwear, semelle EVA anti-fatigue, tige en mesh respirant, renfort talonnière. Disponibles en 8 coloris. Tailles 36–45. Emballage boîte individuelle.",
    features: ["Semelle EVA cushion", "8 coloris disponibles", "Tailles 36 à 45", "Tige mesh respirante", "Boîte individuelle incluse"],
    specifications: [
      { label: "Matière tige", value: "Mesh PU respirant" },
      { label: "Semelle", value: "EVA antidérapant" },
      { label: "Tailles", value: "36 à 45 EU" },
      { label: "Minimum commande", value: "5 paires" },
    ],
    reviews: [],
    related: ["6", "8", "10"],
  },
  {
    id: "5",
    title: "Sérum Visage Vitamine C Éclat",
    subtitle: "Soin anti-tâches — Formule concentrée 30ml",
    price: 950,
    oldPrice: 1600,
    minQty: 10,
    image: "/images/assets/item_5.jpg",
    images: ["/images/assets/item_5.jpg"],
    category: "beauty",
    origin: "Hub International Europe & Asie",
    weight: "0.08 kg",
    volume: "0.0005 CBM",
    rating: 4.8,
    reviewsCount: 415,
    description: "Sérum concentré à la Vitamine C 20%, acide hyaluronique et niacinamide. Formule anti-tâches, unificatrice du teint. Conditionnement 30ml avec pipette de précision. Certification cosmétique ISO.",
    features: ["Vitamine C 20% stabilisée", "Acide hyaluronique", "Niacinamide 5%", "30ml + pipette", "Certification ISO cosmétique"],
    specifications: [
      { label: "Contenance", value: "30 ml" },
      { label: "Contenant", value: "Flacon verre ambré" },
      { label: "Certification", value: "ISO 22716" },
      { label: "Minimum commande", value: "10 unités" },
    ],
    reviews: [],
    related: [],
  },
  {
    id: "6",
    title: "T-Shirt Graphic Streetwear Red Edition",
    subtitle: "Collection capsule — 100% Coton Premium",
    price: 1200,
    oldPrice: 2000,
    minQty: 10,
    image: "/images/assets/item_6.jpg",
    images: ["/images/assets/item_6.jpg", "/images/assets/item_8.jpg"],
    category: "fashion",
    origin: "Hub Asie & International",
    weight: "0.20 kg",
    volume: "0.002 CBM",
    rating: 4.3,
    reviewsCount: 221,
    description: "T-shirt oversize en coton 100% ring-spun 180g/m². Sérigraphie haute définition résistante aux lavages. Coupe streetwear ample. Disponible en S à 3XL.",
    features: ["Coton 100% ring-spun 180g/m²", "Sérigraphie HD lavable", "Coupe oversize", "Tailles S à 3XL"],
    specifications: [
      { label: "Matière", value: "100% Coton 180g/m²" },
      { label: "Impression", value: "Sérigraphie HD" },
      { label: "Tailles", value: "S à 3XL" },
      { label: "Minimum commande", value: "10 pièces" },
    ],
    reviews: [],
    related: ["4", "8"],
  },
  {
    id: "7",
    title: "Coffret Bijoux Doré 24k Luxury",
    subtitle: "Coffret bijoux plaqué or — Édition cadeau premium",
    price: 1800,
    oldPrice: 3000,
    minQty: 5,
    image: "/images/assets/item_7.jpg",
    images: ["/images/assets/item_7.jpg"],
    category: "fashion",
    badge: "TENDANCE",
    origin: "Hub Grossistes International",
    weight: "0.18 kg",
    volume: "0.001 CBM",
    rating: 4.6,
    reviewsCount: 87,
    description: "Coffret 5 pièces (bague, boucles, bracelet, collier, pendentif) plaqué or 24k anti-allergique. Boîte cadeau velours avec ruban. Idéal fête des mères, mariages, boutiques cadeaux.",
    features: ["Plaquage or 24k", "5 pièces par coffret", "Boîte velours incluse", "Anti-allergique", "Certifié nickel-free"],
    specifications: [
      { label: "Matière", value: "Alliage plaqué or 24k" },
      { label: "Pièces", value: "5 (bague, boucles, bracelet, collier, pendentif)" },
      { label: "Certification", value: "Nickel-free EU" },
      { label: "Minimum commande", value: "5 coffrets" },
    ],
    reviews: [],
    related: ["1", "4"],
  },
  {
    id: "8",
    title: "Veste Blouson Imperméable Workwear",
    subtitle: "Vêtement de travail — Coupe cargo utilitaire",
    price: 3200,
    oldPrice: 5000,
    minQty: 5,
    image: "/images/assets/item_8.jpg",
    images: ["/images/assets/item_8.jpg", "/images/assets/item_6.jpg"],
    category: "fashion",
    origin: "Hub Asie & International",
    weight: "0.6 kg",
    volume: "0.006 CBM",
    rating: 4.4,
    reviewsCount: 134,
    description: "Blouson de travail imperméable en polyester 600D avec doublure polaire amovible. 6 poches multi-fonctions, fermetures éclair YKK. Logo personnalisable sur commande >100 pièces.",
    features: ["Imperméable polyester 600D", "Doublure polaire amovible", "6 poches", "Fermetures YKK", "Logo personnalisable >100u"],
    specifications: [
      { label: "Matière", value: "Polyester 600D imperméable" },
      { label: "Doublure", value: "Polaire amovible" },
      { label: "Fermetures", value: "YKK" },
      { label: "Minimum commande", value: "5 pièces" },
    ],
    reviews: [],
    related: ["4", "6"],
  },
  {
    id: "9",
    title: "Gants Protection & Travail Cuir",
    subtitle: "EPI industriel — Norme EN388 certifiés",
    price: 750,
    oldPrice: 1400,
    minQty: 10,
    image: "/images/assets/item_9.jpg",
    images: ["/images/assets/item_9.jpg"],
    category: "machinery",
    origin: "Hub International Usines",
    weight: "0.12 kg",
    volume: "0.0008 CBM",
    rating: 4.5,
    reviewsCount: 298,
    description: "Gants de protection en cuir fleur bovin avec renforts anti-coupure. Poignet velcro réglable. Certification EN388 niveau 4. Conditionnement paire individuelle + étiquetage personnalisable.",
    features: ["Cuir fleur bovin", "Anti-coupure EN388 Niv.4", "Poignet velcro réglable", "Étiquetage personnalisable"],
    specifications: [
      { label: "Matière", value: "Cuir fleur bovin" },
      { label: "Certification", value: "EN388 niveau 4" },
      { label: "Tailles", value: "S, M, L, XL" },
      { label: "Minimum commande", value: "10 paires" },
    ],
    reviews: [],
    related: [],
  },
  {
    id: "10",
    title: "Parka Rembourrée Capuche Fourrure",
    subtitle: "Manteau d'hiver — Garnissage duvet synthétique",
    price: 4800,
    oldPrice: 7500,
    minQty: 5,
    image: "/images/assets/item_10.jpg",
    images: ["/images/assets/item_10.jpg", "/images/assets/item_8.jpg"],
    category: "fashion",
    origin: "Hub International Usines",
    weight: "0.9 kg",
    volume: "0.008 CBM",
    rating: 4.7,
    reviewsCount: 67,
    description: "Parka longue rembourrée duvet synthétique 80g, capuche amovible à fausse fourrure, imperméable DWR. Idéal hivernage, zones climatisées. Tailles S à 2XL.",
    features: ["Garnissage duvet synthétique 80g", "Capuche fourrure amovible", "Imperméable DWR", "Tailles S à 2XL"],
    specifications: [
      { label: "Matière", value: "Polyester DWR imperméable" },
      { label: "Garnissage", value: "Duvet synthétique 80g/m²" },
      { label: "Capuche", value: "Amovible — fausse fourrure" },
      { label: "Minimum commande", value: "5 pièces" },
    ],
    reviews: [],
    related: ["6", "8"],
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(ids: string[]): Product[] {
  return PRODUCTS.filter((p) => ids.includes(p.id)).slice(0, 4);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
