// Catalogue centralisé des produits CargoLink Africa
// Ce fichier est la source de vérité partagée entre /catalog, /product/[id], et la homepage

export interface Product {
  id: string;
  title: string;
  subtitle: string;
  price: number; // prix unitaire FCFA
  oldPrice?: number;
  minQty: number;
  maxQty?: number;
  image: string;
  images: string[];
  category: string;
  badge?: string;
  origin: string;
  weight: string; // ex: "0.35 kg"
  volume: string; // ex: "0.002 CBM"
  rating: number;
  reviewsCount: number;
  description: string;
  features: string[];
  specifications: { label: string; value: string }[];
  reviews: { author: string; rating: number; comment: string; date: string }[];
  related: string[]; // IDs of related products
  // Étiquettes & spécifications téléphone (Catalogue FenouShop)
  conditionState?: "Scellé" | "Reconditionné" | "Occasion";
  grade?: string;
  simType?: string;
  regionVersion?: string;
  storageOptions?: string[];
  batteryHealth?: string;
  driveFolderUrl?: string;
}

export const PRODUCTS: Product[] = [
  // --- CATALOGUE RÉEL IPHONE FENOUSHOP ---
  {
    id: "iphone-7-7plus",
    title: "iPhone 7 & 7 Plus Grossiste (Catalogue FenouShop)",
    subtitle: "Modèles 4.7\" et 5.5\" — État certifié FenouShop",
    price: 26000,
    oldPrice: 35000,
    minQty: 1,
    image: "/images/assets/iphone7/iphone7_gold.png",
    images: [
      "/images/assets/iphone7/iphone7_gold.png",
      "/images/assets/iphone7/iphone7_rosegold.png",
      "/images/assets/iphone7/iphone7_silver.png",
      "/images/assets/iphone7/iphone7_black.png",
      "/images/assets/iphone7/iphone7_jetblack.png",
    ],
    driveFolderUrl: "https://drive.google.com/drive/folders/1y6gmTjsFFKyy2Y_P6ilk16u85KYgeZN2?usp=sharing",
    category: "electronics",
    badge: "PRIX MINIMAL",
    origin: "Chine (FenouShop Partner)",
    weight: "0.14 kg",
    volume: "0.001 CBM",
    rating: 4.6,
    reviewsCount: 142,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["32 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "Lot grossiste d'iPhone 7 et 7 Plus authentiques issus du catalogue FenouShop. Écran Retina HD, processeur A10 Fusion, appareil photo 12 MP et étanchéité IP67. Chaque téléphone subit un contrôle qualité rigoureux (batterie, écran, haut-parleur). Fourchette tarifaire de 26 000 à 72 000 FCFA selon la capacité et le grade.",
    features: [
      "Écran Retina HD 4.7\" / 5.5\"",
      "Puce A10 Fusion performante",
      "Capteur photo 12 MP 4K",
      "Touch ID empreinte digitale",
      "Batterie contrôlée (85% à 100%)",
      "Contrôle qualité FenouShop inclus",
    ],
    specifications: [
      { label: "Marque / Modèle", value: "Apple iPhone 7 & 7 Plus" },
      { label: "État / Condition", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Stockage dispo.", value: "32 Go / 128 Go / 256 Go" },
      { label: "Type SIM", value: "SIM physique" },
      { label: "État Batterie", value: "85% - 100%" },
      { label: "Plage tarifaire", value: "26 000 à 72 000 FCFA" },
      { label: "Garantie", value: "Contrôle avant expédition" },
    ],
    reviews: [
      { author: "Koffi A.", rating: 5, comment: "Reçu en parfait état de fonctionnement à Cotonou. Vendu très rapidement !", date: "12 Fév. 2025" },
    ],
    related: ["iphone-8-8plus", "iphone-x-xr-xsmax", "1"],
  },
  {
    id: "iphone-8-8plus",
    title: "iPhone 8 & 8 Plus Grossiste (Catalogue FenouShop)",
    subtitle: "Dos en verre, Puce A11 Bionic & Charge sans fil",
    price: 33000,
    oldPrice: 45000,
    minQty: 1,
    image: "/images/assets/iphone8/iphone8_gold.png",
    images: [
      "/images/assets/iphone8/iphone8_gold.png",
      "/images/assets/iphone8/iphone8_silver.png",
      "/images/assets/iphone8/iphone8_spacegray.png",
    ],
    driveFolderUrl: "https://drive.google.com/drive/folders/1_f8mhhl7NyxaOUsM-jCdF5eZSooZL286?usp=sharing",
    category: "electronics",
    origin: "Chine (FenouShop Partner)",
    weight: "0.15 kg",
    volume: "0.001 CBM",
    rating: 4.7,
    reviewsCount: 198,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["32 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "Gamme iPhone 8 et 8 Plus direct usine via FenouShop. Design élégant en verre résistant, compatibilité avec la recharge sans fil Qi et processeur A11 Bionic avec Neural Engine. Fourchette tarifaire de 33 000 à 85 000 FCFA selon la version.",
    features: [
      "Dos en verre avec recharge sans fil Qi",
      "Puce A11 Bionic haute rapidité",
      "Écran True Tone Retina HD",
      "Capteur photo 12 MP (Portraits sur 8 Plus)",
      "Vérification batterie & boutons OK",
    ],
    specifications: [
      { label: "Marque / Modèle", value: "Apple iPhone 8 & 8 Plus" },
      { label: "État", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Stockage", value: "32 Go / 128 Go / 256 Go" },
      { label: "SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "33 000 à 85 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-7-7plus", "iphone-x-xr-xsmax", "iphone-11-11pro-11promax"],
  },
  {
    id: "iphone-x-xr-xsmax",
    title: "iPhone X / XR / XS Max Grossiste",
    subtitle: "Écran Super Retina OLED & Face ID sécurisé",
    price: 46000,
    oldPrice: 65000,
    minQty: 1,
    image: "/images/assets/iphonex/iphonex_spacegray.png",
    images: [
      "/images/assets/iphonex/iphonex_spacegray.png",
      "/images/assets/iphonex/iphonex_silver.png",
    ],
    driveFolderUrl: "https://drive.google.com/drive/folders/1FbSidVBOsmF9OQ3j5iV2W-VtamLUAlAt?usp=sharing",
    category: "electronics",
    badge: "POPULAIRE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.17 kg",
    volume: "0.001 CBM",
    rating: 4.8,
    reviewsCount: 310,
    conditionState: "Occasion",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "128 Go", "256 Go"],
    batteryHealth: "85% - 100% origine",
    description:
      "La génération borderless d'Apple : iPhone X, iPhone XR et iPhone XS Max. Écran OLED Super Retina / Liquid Retina HD, déverrouillage Face ID 3D et puce A12 Bionic. Tarifs de 46 000 à 125 000 FCFA selon la configuration.",
    features: [
      "Écran panoramique borderless OLED / Liquid Retina",
      "Face ID ultra rapide et sécurisé",
      "Puce A12 Bionic Neural Engine",
      "Double appareil photo 12 MP (X & XS Max)",
      "Autonomie batterie longue durée (XR)",
    ],
    specifications: [
      { label: "Modèles", value: "iPhone X, XR, XS Max" },
      { label: "État", value: "Occasion Contrôlée (Grade B/C)" },
      { label: "Capacités", value: "64 Go / 128 Go / 256 Go" },
      { label: "Type SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "46 000 à 125 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-8-8plus", "iphone-11-11pro-11promax", "iphone-12-12pro-12promax"],
  },
  {
    id: "iphone-11-11pro-11promax",
    title: "iPhone 11 / 11 Pro / 11 Pro Max Grossiste",
    subtitle: "Triple appareil photo 4K, Mode Nuit & A13 Bionic",
    price: 79000,
    oldPrice: 110000,
    minQty: 1,
    image: "/images/assets/iphone11/iphone11_black.png",
    images: ["/images/assets/iphone11/iphone11_black.png", "/images/assets/card_hero_iphone.jpg"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1ISu5htHPwMzug_bGsqDDME5vrbEDJuSm?usp=sharing",
    category: "electronics",
    badge: "BEST SELLER",
    origin: "Chine (FenouShop Partner)",
    weight: "0.19 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 520,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "256 Go"],
    batteryHealth: "88% - 100%",
    description:
      "Incontournable pour la revente : iPhone 11, 11 Pro et 11 Pro Max reconditionnés. Double ou triple capteur ultra grand-angle, vidéo 4K à 60 ips, autonomie record et verre dépoli ultra résistant. Prix grossiste de 79 000 à 198 000 FCFA.",
    features: [
      "Double / Triple capteur photo 12 MP avec Mode Nuit",
      "Puce A13 Bionic surpuissante",
      "Batterie longue autonomie",
      "Finition verre mat / acier inoxydable (Pro)",
      "Reconditionné certifié FenouShop",
    ],
    specifications: [
      { label: "Série", value: "iPhone 11 / 11 Pro / 11 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Stockages", value: "64 Go / 256 Go" },
      { label: "SIM", value: "SIM physique" },
      { label: "Plage tarifaire", value: "79 000 à 198 000 FCFA" },
    ],
    reviews: [
      { author: "Saliou M.", rating: 5, comment: "Superbe lot d'iPhone 11 Pro. Qualité d'écran et batterie parfaites !", date: "02 Mar. 2025" },
    ],
    related: ["iphone-x-xr-xsmax", "iphone-12-12pro-12promax", "iphone-13-13pro-13promax"],
  },
  {
    id: "iphone-12-12pro-12promax",
    title: "iPhone 12 / 12 Pro / 12 Pro Max Grossiste",
    subtitle: "Design Ceramic Shield, Réseau 5G & MagSafe",
    price: 98000,
    oldPrice: 135000,
    minQty: 1,
    image: "/images/assets/iphone12/iphone12_pacificblue.png",
    images: ["/images/assets/iphone12/iphone12_pacificblue.png", "/images/assets/card_hero_iphone.jpg"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1jGmuaj1z5hKrRtpEopKMtLOyL-PGYEFS?usp=sharing",
    category: "electronics",
    badge: "TENDANCE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.18 kg",
    volume: "0.001 CBM",
    rating: 4.8,
    reviewsCount: 412,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "SIM physique",
    regionVersion: "Version Global",
    storageOptions: ["64 Go", "128 Go", "256 Go"],
    batteryHealth: "88% - 100%",
    description:
      "La révolution 5G avec l'iPhone 12, 12 Pro et 12 Pro Max. Écran Super Retina XDR OLED, façade Ceramic Shield 4x plus résistante aux chutes, scanner LiDAR sur les séries Pro et recharge MagSafe. Tarifs grossistes de 98 000 à 249 000 FCFA.",
    features: [
      "Connexion ultra rapide 5G",
      "Ceramic Shield & bords plats aluminium/acier",
      "Recharge magnétique MagSafe",
      "Scanner LiDAR pour portraits de nuit (Pro)",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 12, 12 Pro, 12 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Capacités", value: "64 Go / 128 Go / 256 Go" },
      { label: "Plage tarifaire", value: "98 000 à 249 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-11-11pro-11promax", "iphone-13-13pro-13promax", "iphone-14-14pro-14promax"],
  },
  {
    id: "iphone-13-13pro-13promax",
    title: "iPhone 13 / 13 Pro / 13 Pro Max Grossiste",
    subtitle: "Puce A15 Bionic, Écran ProMotion 120Hz & Mode Cinéma",
    price: 131000,
    oldPrice: 180000,
    minQty: 1,
    image: "/images/assets/iphone13/iphone13_gold.png",
    images: ["/images/assets/iphone13/iphone13_gold.png", "/images/assets/card_hero_iphone.jpg"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1pWGNnSNlNAc4JY6kUn1rRvcOO7VAjh_e?usp=sharing",
    category: "electronics",
    badge: "TOP VENTES",
    origin: "Chine (FenouShop Partner)",
    weight: "0.20 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 380,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "90% - 100%",
    description:
      "Excellence technologique : iPhone 13, 13 Pro et 13 Pro Max. Encoche réduite de 20%, écran fluide ProMotion 120 Hz, Mode Cinéma pour des vidéos professionnelles avec faible profondeur de champ. Tarifs de 131 000 à 328 000 FCFA.",
    features: [
      "ProMotion 120 Hz adaptatif (13 Pro & Pro Max)",
      "Mode Cinéma automatique avec focus dynamique",
      "Puce A15 Bionic 6-cœurs",
      "Capacité jusqu'à 1 To",
      "Prise en charge eSIM + Dual SIM",
    ],
    specifications: [
      { label: "Série", value: "iPhone 13, 13 Pro, 13 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Type SIM", value: "eSIM / Dual SIM" },
      { label: "Version", value: "Version US (LL/A) / Global" },
      { label: "Plage tarifaire", value: "131 000 à 328 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-12-12pro-12promax", "iphone-14-14pro-14promax", "iphone-15-15pro-15promax"],
  },
  {
    id: "iphone-14-14pro-14promax",
    title: "iPhone 14 / 14 Pro / 14 Pro Max Grossiste",
    subtitle: "Dynamic Island, Capteur 48 MP & Détection d'Accident",
    price: 197000,
    oldPrice: 260000,
    minQty: 1,
    image: "/images/assets/iphone14/iphone14_spaceblack.png",
    images: ["/images/assets/iphone14/iphone14_spaceblack.png", "/images/assets/hero_iphone16.png"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1Qs6ijeFtKX1aj4HobL9nBgy7eI-QtaYw?usp=sharing",
    category: "electronics",
    badge: "BEST SELLER",
    origin: "Chine (FenouShop Partner)",
    weight: "0.21 kg",
    volume: "0.001 CBM",
    rating: 4.9,
    reviewsCount: 290,
    conditionState: "Reconditionné",
    grade: "Grade B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "90% - 100%",
    description:
      "La gamme iPhone 14 avec l'innovation Dynamic Island sur les Pro. Capteur principal 48 MP ProRAW, écran Toujours Activé (Always-On), puce A16 Bionic et détection des accidents de la route. Fourchette tarifaire de 197 000 à 394 000 FCFA.",
    features: [
      "Dynamic Island interactive (Pro & Pro Max)",
      "Capteur photo professionnel 48 MP",
      "Puce A16 Bionic (Pro)",
      "Détection d'accident et SOS urgence",
      "Disponibilité immédiate FenouShop",
    ],
    specifications: [
      { label: "Modèles", value: "iPhone 14, 14 Plus, 14 Pro, 14 Pro Max" },
      { label: "État", value: "Reconditionné Certifié (Grade B/C)" },
      { label: "Compatibilité SIM", value: "eSIM & Dual SIM" },
      { label: "Région", value: "Version US (LL/A)" },
      { label: "Plage tarifaire", value: "197 000 à 394 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-13-13pro-13promax", "iphone-15-15pro-15promax", "iphone-16-16pro-16promax"],
  },
  {
    id: "iphone-15-15pro-15promax",
    title: "iPhone 15 / 15 Pro / 15 Pro Max Grossiste",
    subtitle: "Châssis Titane de qualité spatiale & USB-C Universel",
    price: 230000,
    oldPrice: 310000,
    minQty: 1,
    image: "/images/assets/iphone15/iphone15_bluetitanium.jpg",
    images: ["/images/assets/iphone15/iphone15_bluetitanium.jpg", "/images/assets/hero_iphone16.png"],
    driveFolderUrl: "https://drive.google.com/drive/folders/18GZI_kVisZptLbaawH3LXWV2Y4WvKpYc?usp=sharing",
    category: "electronics",
    badge: "PREMIUM",
    origin: "Chine (FenouShop Partner)",
    weight: "0.19 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 215,
    conditionState: "Scellé",
    grade: "Grade A/B/C",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US / EU",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "100% Scellé / Neuf",
    description:
      "La génération iPhone 15 en version Scellée / Neuf ou Grade A. Conçu en titane ultra léger et résistant, port USB-C 3.0 ultra rapide, bouton Action personnalisable et zoom optique 5x (Pro Max). Tarifs grossistes de 230 000 à 492 000 FCFA.",
    features: [
      "Design Titane ultra léger et robuste",
      "Connectique universelle USB-C",
      "Bouton Action programmable",
      "Puce A17 Pro gravée en 3nm",
      "Zoom optique 5x télescopique (Pro Max)",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 15, 15 Plus, 15 Pro, 15 Pro Max" },
      { label: "État produit", value: "Scellé / Neuf & Grade A/B/C" },
      { label: "Connecteur", value: "USB-C" },
      { label: "SIM", value: "eSIM / Dual SIM physique" },
      { label: "Plage tarifaire", value: "230 000 à 492 000 FCFA" },
    ],
    reviews: [
      { author: "Rodrigue T.", rating: 5, comment: "Reçu l'iPhone 15 Pro Max scellé en boîte d'origine. Produit 100% authentique !", date: "15 Jan. 2025" },
    ],
    related: ["iphone-14-14pro-14promax", "iphone-16-16pro-16promax", "iphone-17-17pro-17promax"],
  },
  {
    id: "iphone-16-16pro-16promax",
    title: "iPhone 16 / 16 Pro / 16 Pro Max Grossiste",
    subtitle: "Apple Intelligence & Nouveau Bouton Commande de l'Appareil Photo",
    price: 295000,
    oldPrice: 380000,
    minQty: 1,
    image: "/images/assets/hero_iphone16.png",
    images: ["/images/assets/hero_iphone16.png", "/images/assets/card_hero_iphone.jpg"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1quRc7S5h9nUlMOU4t7krrYV-RhHKmaWa?usp=sharing",
    category: "electronics",
    badge: "NOUVEAU",
    origin: "Chine (FenouShop Partner)",
    weight: "0.20 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 165,
    conditionState: "Scellé",
    grade: "Grade A",
    simType: "eSIM & Dual SIM",
    regionVersion: "Version US (LL/A)",
    storageOptions: ["128 Go", "256 Go", "512 Go", "1 To"],
    batteryHealth: "100% Neuf d'origine",
    description:
      "Dernier né d'Apple : l'iPhone 16, 16 Pro et 16 Pro Max. Intégration d'Apple Intelligence, nouveau bouton de contrôle tactile pour la caméra, puce A18 / A18 Pro et enregistrement vidéo 4K 120 ips Dolby Vision. Prix de 295 000 à 623 000 FCFA.",
    features: [
      "Bouton haptique Commande de la Caméra",
      "Puce A18 Pro optimisée IA",
      "Écrans agrandis 6.3\" et 6.9\" (Pro)",
      "Vidéo 4K 120 ips Dolby Vision",
      "Produits 100% Scellés avec boite scellée",
    ],
    specifications: [
      { label: "Série", value: "iPhone 16, 16 Plus, 16 Pro, 16 Pro Max" },
      { label: "État", value: "Scellé / Neuf (Grade A Premium)" },
      { label: "Puce", value: "Apple A18 & A18 Pro" },
      { label: "Plage tarifaire", value: "295 000 à 623 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-15-15pro-15promax", "iphone-17-17pro-17promax"],
  },
  {
    id: "iphone-17-17pro-17promax",
    title: "iPhone 17 / 17 Pro / 17 Pro Max (Avant-Première)",
    subtitle: "Nouvelle Génération Apple A19 Pro & Refroidissement Chambre à Vapeur",
    price: 394000,
    oldPrice: 520000,
    minQty: 1,
    image: "/images/assets/hero_iphone16.png",
    images: ["/images/assets/hero_iphone16.png"],
    driveFolderUrl: "https://drive.google.com/drive/folders/1MQ6F-SZHMqsn5y2zcEDGA2BxpPWbbAe3?usp=sharing",
    category: "electronics",
    badge: "AVANT-PREMIÈRE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.21 kg",
    volume: "0.001 CBM",
    rating: 5.0,
    reviewsCount: 42,
    conditionState: "Scellé",
    grade: "Grade A",
    simType: "Dual SIM",
    regionVersion: "Version Global",
    storageOptions: ["256 Go", "512 Go", "1 To", "2 To"],
    batteryHealth: "100% Neuf d'origine",
    description:
      "La future référence d'Apple proposée en réservation grossiste par FenouShop. Puce A19 Pro, jusqu'à 2 To de stockage, système thermique à chambre à vapeur et capteurs ultra avancés. Tarifs indicatifs de 394 000 à 886 000 FCFA.",
    features: [
      "Puce A19 Pro nouvelle génération",
      "Système thermique avancé par chambre à vapeur",
      "Stockage étendu jusqu'à 2 To",
      "Design avant-gardiste ultra fin",
    ],
    specifications: [
      { label: "Gamme", value: "iPhone 17, 17 Pro, 17 Pro Max" },
      { label: "État", value: "Scellé / Neuf d'origine" },
      { label: "Stockage max.", value: "Jusqu'à 2 To" },
      { label: "Plage tarifaire", value: "394 000 à 886 000 FCFA" },
    ],
    reviews: [],
    related: ["iphone-16-16pro-16promax"],
  },
  {
    id: "iphone-16-rugged-case",
    title: "Coque Blindée Tri-Couche iPhone 16 avec Protège Écran & Béquille",
    subtitle: "Protection Militaire Anti-Choc 360°, Rebord Caméra Surélevé 3.5mm & Support Intégré",
    price: 3500,
    oldPrice: 6500,
    minQty: 2,
    image: "/images/assets/iphone16_case/case_purple.png",
    images: [
      "/images/assets/iphone16_case/case_purple.png",
      "/images/assets/iphone16_case/case_black.png",
      "/images/assets/iphone16_case/case_features.png",
    ],
    category: "electronics",
    badge: "ACCESSOIRE USINE",
    origin: "Chine (Usine Partenaire FenouShop)",
    weight: "0.09 kg",
    volume: "0.0005 CBM",
    rating: 4.9,
    reviewsCount: 184,
    conditionState: "Scellé",
    grade: "Grade A",
    description:
      "Coque renforcée militaire Tri-Couche ultra-résistante pour iPhone 16 (6.1\"). Livrée avec verre trempé écran haute transparence, béquille invisible intégrée et rebord surélevé de 3.5mm pour la protection complète des objectifs photos. Disponible en Violet et Noir.",
    features: [
      "Protection Militaire Tri-Couche Anti-Choc & Chutes",
      "Protège-Écran en Verre Trempé haute résistance inclus",
      "Béquille invisible intégrée pour visionnage vidéo Hands-Free",
      "Rebord surélevé de 3.5mm pour préserver les appareils photos",
      "Disponible en Violet (Purple) et Noir Tactique",
    ],
    specifications: [
      { label: "Modèle compatible", value: "iPhone 16 (6.1 pouces)" },
      { label: "Type de protection", value: "Tri-Couche Militaire 360°" },
      { label: "Verre Trempé", value: "Inclus dans le pack usine" },
      { label: "Béquille", value: "Invisible & Escamotable" },
      { label: "Coloris dispo.", value: "Violet / Purple & Noir" },
    ],
    reviews: [],
    related: ["iphone-16-16pro-16promax"],
  },
  {
    id: "disaar-creme-depilatoire",
    title: "Disaar Crème Dépilatoire – Épilation Rapide 3 Minutes (100 g)",
    subtitle: "Épilation douce & réduction de la pousse des poils sans irritation",
    price: 2500,
    oldPrice: 4000,
    minQty: 1,
    image: "/images/assets/disaar_hair_removal.jpg",
    images: [
      "/images/assets/disaar_hair_removal.jpg",
      "/images/assets/cat_beauty.jpg",
    ],
    category: "beauty",
    badge: "BEAUTÉ & SOINS",
    origin: "Chine (FenouShop Partner)",
    weight: "0.10 kg",
    volume: "0.0003 CBM",
    rating: 4.9,
    reviewsCount: 124,
    conditionState: "Scellé",
    grade: "Grade A",
    description:
      "Marque : DISAAR. Contenance : 100ml / 100g. Efficacité : douce et n'irrite pas la peau. Contient des facteurs dépilatoires qui peuvent ramollir et étirer les follicules pileux, facilement absorbés par le corps humain ou la peau. Réduit la sécrétion des glandes sudoripares, rétrécit les pores et les follicules pileux. Propre, durable, facile à enlever ou à rincer et rend la peau lisse et hydratée. Épilation douce sur les bras, poils du bikini, lèvres supérieures, aisselles, jambes, visage, zone pubienne et autres zones du corps.",
    features: [
      "Épilation ultra-rapide 3 minutes douce et sans douleur",
      "Facteurs dépilatoires réducteurs de repousse des poils",
      "Rétrécit les pores & hydrate la peau en profondeur",
      "Convient pour bras, aisselles, maillot, jambes, visage et zone pubienne",
      "Contrôle de qualité professionnel épilation + réduction pousse",
    ],
    specifications: [
      { label: "Marque", value: "DISAAR Beauty Skincare" },
      { label: "Contenance / Contenu", value: "100 g / 100 ml" },
      { label: "Temps d'action", value: "3 à 8 minutes" },
      { label: "Zones d'application", value: "Corps, bras, aisselles, bikini, jambes, visage" },
      { label: "Propriétés", value: "Épilation douce & Réduction pousse" },
      { label: "État / Condition", value: "Neuf Scellé" },
    ],
    reviews: [
      { author: "Amina K.", rating: 5, comment: "Crème très efficace et douce, ne brûle pas du tout la peau !", date: "18 Fév. 2025" },
    ],
    related: ["cat_beauty"],
  },
  {
    id: "efero-blanchiment-dents",
    title: "EFERO Essence de Blanchiment des Dents & Hygiène Buccale (10 ml)",
    subtitle: "Élimine les taches de thé, café, plaque dentaire & améliore l'hygiène buccale",
    price: 2500,
    oldPrice: 4500,
    minQty: 1,
    image: "/images/assets/efero_teeth_whitening.jpg",
    images: [
      "/images/assets/efero_teeth_whitening.jpg",
      "/images/assets/cat_beauty.jpg",
    ],
    category: "beauty",
    badge: "HYGIÈNE BUCCALE",
    origin: "Chine (FenouShop Partner)",
    weight: "0.05 kg",
    volume: "0.0001 CBM",
    rating: 4.9,
    reviewsCount: 158,
    conditionState: "Scellé",
    grade: "Grade A",
    description:
      "Marque : EFERO. Contenance : 10 ml. Efficacité : formule ultra-performante pour éliminer les taches de thé, café, tabac, dents pigmentées et plaque dentaire. Blanchit les dents, réduit la saleté dentaire, améliore l'hygiène buccale et réduit les maladies buccales. Posologie : Avant l'utilisation, veuillez nettoyer la bouche avec de l'eau tiède, puis utilisez un coton-tige pour tremper la quantité appropriée du produit, essuyez la surface des dents uniformément et rincez-la à l'eau claire après 15-20 minutes. Recommandation : 2 à 3 fois par semaine.",
    features: [
      "Élimine efficacement taches de café, thé, tabac et plaque dentaire",
      "Blanchit les dents & réduit la saleté dentaire pour un sourire éclatant",
      "Améliore l'hygiène buccale & réduit les risques d'affections gingivales",
      "Application facile et précise au coton-tige",
      "Recommandé 2 à 3 fois par semaine (résultat visible rapide)",
    ],
    specifications: [
      { label: "Marque", value: "EFERO Oral Care" },
      { label: "Contenance / Contenu", value: "10 ml" },
      { label: "Fonction principale", value: "Blanchiment & Élimination de la plaque" },
      { label: "Fréquence d'utilisation", value: "2 à 3 fois par semaine" },
      { label: "Temps d'application", value: "15 à 20 minutes" },
      { label: "État / Condition", value: "Neuf Scellé" },
    ],
    reviews: [
      { author: "Marc O.", rating: 5, comment: "Incroyable résultat dès la première semaine ! Mes taches de café ont complètement disparu.", date: "20 Fév. 2025" },
    ],
    related: ["disaar-creme-depilatoire", "cat_beauty"],
  },
  {
    id: "disaar-masque-vitamine-c",
    title: "Disaar Masque Visage Hydratant Vitamine C & Acide Hyaluronique",
    subtitle: "Rajeunissant, réparateur & coup d'éclat effet SPA rafraîchissant",
    price: 500,
    oldPrice: 1200,
    minQty: 1,
    image: "/images/assets/disaar_vitamin_c_mask.jpg",
    images: [
      "/images/assets/disaar_vitamin_c_mask.jpg",
      "/images/assets/cat_beauty.jpg",
    ],
    category: "beauty",
    badge: "HYDRATATION & ÉCLAT",
    origin: "Chine (FenouShop Partner)",
    weight: "0.03 kg",
    volume: "0.0001 CBM",
    rating: 4.9,
    reviewsCount: 210,
    conditionState: "Scellé",
    grade: "Grade A",
    description:
      "Marque : DISAAR Beauty Skincare. Formulé avec des ingrédients rajeunissants à la Vitamine C et Acide Hyaluronique pour offrir à la peau un soin souple et hydraté. Apporte une expérience rafraîchissante unique. Riche en essence hydratante de haute pureté. Masque en pur coton absorbant la saleté et l'excès de sébum tout en hydratant en profondeur. Enrichi en vitamines, minéraux et antioxydants. Favorise la régénération de la peau pour réparer les peaux sèches et sensibles, réduire les rougeurs, réparer la couche cornée et offrir un véritable effet SPA hydratant continu.",
    features: [
      "Formule concentrée Vitamine C + Acide Hyaluronique + Glutathion de baies",
      "Masque 100% pur coton absorbant le sébum et la saleté",
      "Hydratation en profondeur & réparation des peaux sèches et sensibles",
      "Effet rajeunissant, améliore la souplesse et réduit la sensibilité",
      "Expérience fraîcheur instantanée type SPA à domicile",
    ],
    specifications: [
      { label: "Marque", value: "DISAAR Beauty Skincare" },
      { label: "Actifs principaux", value: "Vitamine C & Acide Hyaluronique" },
      { label: "Matière du masque", value: "Pur Coton doux & respirant" },
      { label: "Type de peau", value: "Tous types de peaux, y compris sensibles" },
      { label: "Action", value: "Hydratation continuous, Éclat & Anti-âge" },
      { label: "État / Condition", value: "Neuf Scellé Sachet individuel" },
    ],
    reviews: [
      { author: "Clarisse N.", rating: 5, comment: "Incroyable sensation de fraîcheur ! Ma peau est super douce et lumineuse dès le premier masque.", date: "21 Fév. 2025" },
    ],
    related: ["disaar-creme-depilatoire", "efero-blanchiment-dents", "cat_beauty"],
  },
  {
    id: "masque-levres-rose-hydrogel",
    title: "Masque Lèvres Rose Hydrogel Hydratant & Repulpant au Collagène",
    subtitle: "Soin SOS lèvres gercées, nutrition intense & lissage avant maquillage",
    price: 500,
    oldPrice: 1200,
    minQty: 1,
    image: "/images/assets/pink_lip_mask.jpg",
    images: [
      "/images/assets/pink_lip_mask.jpg",
      "/images/assets/cat_beauty.jpg",
    ],
    category: "beauty",
    badge: "SOIN LÈVRES",
    origin: "Chine (FenouShop Partner)",
    weight: "0.02 kg",
    volume: "0.0001 CBM",
    rating: 4.9,
    reviewsCount: 185,
    conditionState: "Scellé",
    grade: "Grade A",
    description:
      "Masque patch pour lèvres rose au collagène et hydrogel. Allié indispensable contre le dessèchement et les agressions extérieures (baisse de température, froid, vent). Le geste malin : s'applique le matin avant de se maquiller ou le soir après le démaquillage. Associe son pouvoir ultra-hydratant avec votre baume à lèvres fétiche pour des lèvres douces, lisses, nourries et naturellement repulpées.",
    features: [
      "Patch hydrogel au collagène rose lissant & repulpant",
      "Hydratation intense SOS contre le dessèchement des lèvres",
      "S'applique 15-20 min le matin (pré-maquillage) ou le soir",
      "Prépare les lèvres pour une tenue parfaite du rouge à lèvres",
      "Format individuel stérile scellé à emporter partout",
    ],
    specifications: [
      { label: "Type de produit", value: "Masque Lèvres Hydrogel Patch" },
      { label: "Actifs principaux", value: "Collagène, Acide Hyaluronique, Extrait de Rose" },
      { label: "Utilisation conseillée", value: "Matin (avant maquillage) / Soir (après démaquillage)" },
      { label: "Temps de pose", value: "15 à 20 minutes" },
      { label: "Bénéfice", value: "Hydratation intense & Lèvres lisses" },
      { label: "État / Condition", value: "Neuf Scellé Sachet individuel" },
    ],
    reviews: [
      { author: "Sandrine K.", rating: 5, comment: "Indispensable avant le rouge à lèvres ! Mes lèvres ne gercent plus du tout.", date: "22 Fév. 2025" },
    ],
    related: ["disaar-masque-vitamine-c", "disaar-creme-depilatoire", "cat_beauty"],
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(ids: string[]): Product[] {
  return PRODUCTS.filter((p) => ids.includes(p.id)).slice(0, 4);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
