import type { Order, Profile, Quote, Shipment, Payment, Dispute, Notification, Supplier } from "@/types/supabase";

export const DEMO_QUOTES: Quote[] = [
  { id: "q1", quote_number: "DEV-2026-881234", user_id: "u1", user_name: "Jean Koffi", user_email: "jean.koffi@gmail.com", product_name: "Casques Bluetooth ANC TWS", product_link: "https://supplier-catalog.com/item/12345.html", quantity: 200, shipping_mode: "air", destination_city: "Cotonou", destination_country: "Bénin", status: "new", product_cost: 2800000, service_fee: 140000, shipping_fee: 450000, extra_fee: 0, total_amount: 3390000, admin_notes: "", expiration_date: null, estimated_price: 14000, estimated_weight: 60, created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), updated_at: new Date().toISOString() },
  { id: "q2", quote_number: "DEV-2026-773421", user_id: "u2", user_name: "Aminata Diallo", user_email: "aminata.d@gmail.com", product_name: "Baskets Running Sport Nike Style", product_link: "https://supplier-catalog.com/item/67890.html", quantity: 50, shipping_mode: "sea", destination_city: "Lomé", destination_country: "Togo", status: "under_review", product_cost: 1250000, service_fee: 62500, shipping_fee: 185000, extra_fee: 15000, total_amount: 1512500, admin_notes: "Vérification taille disponible 40-45 requise", expiration_date: null, estimated_price: 25000, estimated_weight: 30, created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(), updated_at: new Date().toISOString() },
  { id: "q3", quote_number: "DEV-2026-664890", user_id: "u3", user_name: "Ibrahim Sow", user_email: "ibrahim.sow@business.sn", product_name: "Panneaux Solaires 550W Monocristallin", product_link: "https://supplier-catalog.com/product/solar-550w", quantity: 20, shipping_mode: "sea", destination_city: "Dakar", destination_country: "Sénégal", status: "quote_sent", product_cost: 4200000, service_fee: 210000, shipping_fee: 740000, extra_fee: 30000, total_amount: 5180000, admin_notes: "Devis envoyé le 27/07. Attente confirmation client.", expiration_date: new Date(Date.now() + 7 * 86400000).toISOString(), estimated_price: 210000, estimated_weight: 460, created_at: new Date(Date.now() - 3 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "q4", quote_number: "DEV-2026-558021", user_id: "u4", user_name: "Fatou Koné", user_email: "fatou.kone@gmail.com", product_name: "Sacs à Main Cuir Véritable", product_link: "https://supplier-catalog.com/item/99012.html", quantity: 30, shipping_mode: "air", destination_city: "Abidjan", destination_country: "Côte d'Ivoire", status: "accepted", product_cost: 900000, service_fee: 45000, shipping_fee: 262500, extra_fee: 10000, total_amount: 1217500, admin_notes: "Commande validée, paiement reçu.", expiration_date: null, estimated_price: 30000, estimated_weight: 35, created_at: new Date(Date.now() - 5 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "q5", quote_number: "DEV-2026-441902", user_id: "u5", user_name: "Paul Mbeki", user_email: "paul.mbeki@company.cm", product_name: "Groupes Électrogènes 5kW Diesel", product_link: "https://supplier-catalog.com/product/generator-5kw", quantity: 5, shipping_mode: "sea", destination_city: "Douala", destination_country: "Cameroun", status: "expired", product_cost: 3750000, service_fee: 187500, shipping_fee: 550000, extra_fee: 0, total_amount: 4487500, admin_notes: "Devis expiré — relancer le client.", expiration_date: new Date(Date.now() - 2 * 86400000).toISOString(), estimated_price: 750000, estimated_weight: 350, created_at: new Date(Date.now() - 10 * 86400000).toISOString(), updated_at: new Date().toISOString() },
];

export const DEMO_ORDERS: Order[] = [
  { id: "o1", order_number: "CMD-2026-1231", quote_id: "q4", user_id: "u4", amount: 1217500, currency: "XOF", payment_status: "paid", order_status: "processing", shipping_mode: "air", destination_country: "Côte d'Ivoire", destination_city: "Abidjan", assigned_agent_id: null, supplier_id: null, created_at: new Date(Date.now() - 4 * 86400000).toISOString(), updated_at: new Date().toISOString(), profile: { id: "u4", first_name: "Fatou", last_name: "Koné", email: "fatou.kone@gmail.com", phone: "+225 07 12 34 56", country: "Côte d'Ivoire", city: "Abidjan", account_type: "individual", role: "customer", status: "active", avatar_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() } },
  { id: "o2", order_number: "CMD-2026-0982", quote_id: "q3", user_id: "u3", amount: 5180000, currency: "XOF", payment_status: "pending", order_status: "pending_payment", shipping_mode: "sea", destination_country: "Sénégal", destination_city: "Dakar", assigned_agent_id: null, supplier_id: null, created_at: new Date(Date.now() - 2 * 86400000).toISOString(), updated_at: new Date().toISOString(), profile: { id: "u3", first_name: "Ibrahim", last_name: "Sow", email: "ibrahim.sow@business.sn", phone: "+221 77 00 11 22", country: "Sénégal", city: "Dakar", account_type: "business", role: "customer", status: "active", avatar_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() } },
  { id: "o3", order_number: "CMD-2026-0871", quote_id: null, user_id: "u1", amount: 3390000, currency: "XOF", payment_status: "paid", order_status: "shipped", shipping_mode: "air", destination_country: "Bénin", destination_city: "Cotonou", assigned_agent_id: null, supplier_id: null, created_at: new Date(Date.now() - 6 * 86400000).toISOString(), updated_at: new Date().toISOString(), profile: { id: "u1", first_name: "Jean", last_name: "Koffi", email: "jean.koffi@gmail.com", phone: "+229 97 12 34 56", country: "Bénin", city: "Cotonou", account_type: "individual", role: "customer", status: "active", avatar_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() } },
  { id: "o4", order_number: "CMD-2026-0640", quote_id: null, user_id: "u5", amount: 2850000, currency: "XOF", payment_status: "paid", order_status: "delivered", shipping_mode: "sea", destination_country: "Togo", destination_city: "Lomé", assigned_agent_id: null, supplier_id: null, created_at: new Date(Date.now() - 35 * 86400000).toISOString(), updated_at: new Date().toISOString(), profile: { id: "u5", first_name: "Kofi", last_name: "Agbeko", email: "k.agbeko@gmail.com", phone: "+228 90 45 67 89", country: "Togo", city: "Lomé", account_type: "individual", role: "customer", status: "active", avatar_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() } },
];

export const DEMO_USERS: Profile[] = [
  { id: "u1", first_name: "Jean", last_name: "Koffi", email: "jean.koffi@gmail.com", phone: "+229 97 12 34 56", country: "Bénin", city: "Cotonou", role: "customer", status: "active", account_type: "individual", avatar_url: null, last_activity: new Date(Date.now() - 2 * 3600000).toISOString(), notes: null, created_at: new Date(Date.now() - 30 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "u2", first_name: "Aminata", last_name: "Diallo", email: "aminata.d@gmail.com", phone: "+228 90 55 22 11", country: "Togo", city: "Lomé", role: "customer", status: "active", account_type: "individual", avatar_url: null, last_activity: new Date(Date.now() - 1 * 86400000).toISOString(), notes: null, created_at: new Date(Date.now() - 45 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "u3", first_name: "Ibrahim", last_name: "Sow", email: "ibrahim.sow@business.sn", phone: "+221 77 00 11 22", country: "Sénégal", city: "Dakar", role: "customer", status: "active", account_type: "business", avatar_url: null, last_activity: new Date(Date.now() - 3 * 3600000).toISOString(), notes: "Importateur régulier", created_at: new Date(Date.now() - 60 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "u4", first_name: "Fatou", last_name: "Koné", email: "fatou.kone@gmail.com", phone: "+225 07 12 34 56", country: "Côte d'Ivoire", city: "Abidjan", role: "customer", status: "active", account_type: "individual", avatar_url: null, last_activity: new Date(Date.now() - 4 * 86400000).toISOString(), notes: null, created_at: new Date(Date.now() - 20 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "u5", first_name: "Paul", last_name: "Mbeki", email: "paul.mbeki@company.cm", phone: "+237 699 00 11 22", country: "Cameroun", city: "Douala", role: "customer", status: "suspended", account_type: "business", avatar_url: null, last_activity: new Date(Date.now() - 10 * 86400000).toISOString(), notes: "Compte suspendu — litige paiement", created_at: new Date(Date.now() - 90 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "demo-admin-id", first_name: "Administrateur", last_name: "CargoLink", email: "admin@cargolink.africa", phone: "+229 97 00 00 00", country: "Bénin", city: "Cotonou", role: "admin", status: "active", account_type: "business", avatar_url: null, last_activity: new Date().toISOString(), notes: "Compte administrateur principal", created_at: new Date(Date.now() - 365 * 86400000).toISOString(), updated_at: new Date().toISOString() },
];

export const DEMO_SHIPMENTS: Shipment[] = [
  { id: "s1", order_id: "o3", tracking_number: "CLA-AIR-71009", carrier: "DHL Express", shipping_mode: "air", destination_city: "Cotonou", destination_country: "Bénin", status: "in_transit", estimated_arrival: new Date(Date.now() + 3 * 86400000).toISOString(), weight: 45, volume: 0.3, created_at: new Date(Date.now() - 6 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "s2", order_id: "o1", tracking_number: "CLA-AIR-88234", carrier: "FedEx International", shipping_mode: "air", destination_city: "Abidjan", destination_country: "Côte d'Ivoire", status: "customs_clearance", estimated_arrival: new Date(Date.now() + 1 * 86400000).toISOString(), weight: 28, volume: 0.2, created_at: new Date(Date.now() - 8 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "s3", order_id: "o4", tracking_number: "CLA-SEA-44201", carrier: "Maersk Line", shipping_mode: "sea", destination_city: "Lomé", destination_country: "Togo", status: "delivered", estimated_arrival: new Date(Date.now() - 3 * 86400000).toISOString(), weight: 180, volume: 2.5, created_at: new Date(Date.now() - 38 * 86400000).toISOString(), updated_at: new Date().toISOString() },
  { id: "s4", order_id: "o2", tracking_number: "CLA-SEA-99001", carrier: "CMA CGM", shipping_mode: "sea", destination_city: "Dakar", destination_country: "Sénégal", status: "pending", estimated_arrival: new Date(Date.now() + 35 * 86400000).toISOString(), weight: 460, volume: 5.2, created_at: new Date(Date.now() - 2 * 86400000).toISOString(), updated_at: new Date().toISOString() },
];

export const DEMO_PAYMENTS: Payment[] = [
  { id: "p1", payment_ref: "PAY-2026-001", user_id: "u1", order_id: "o3", amount: 3390000, currency: "XOF", payment_method: "mobile_money", status: "paid", created_at: new Date(Date.now() - 6 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[2], profile: DEMO_USERS[0] },
  { id: "p2", payment_ref: "PAY-2026-002", user_id: "u4", order_id: "o1", amount: 1217500, currency: "XOF", payment_method: "bank_transfer", status: "paid", created_at: new Date(Date.now() - 4 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[0], profile: DEMO_USERS[3] },
  { id: "p3", payment_ref: "PAY-2026-003", user_id: "u3", order_id: "o2", amount: 5180000, currency: "XOF", payment_method: "bank_transfer", status: "pending", created_at: new Date(Date.now() - 2 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[1], profile: DEMO_USERS[2] },
  { id: "p4", payment_ref: "PAY-2026-004", user_id: "u5", order_id: "o4", amount: 2850000, currency: "XOF", payment_method: "mobile_money", status: "paid", created_at: new Date(Date.now() - 35 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[3], profile: DEMO_USERS[4] },
];

export const DEMO_DISPUTES: Dispute[] = [
  { id: "d1", ticket_number: "TKT-2026-01", user_id: "u1", order_id: "o3", subject: "Colis endommagé à la réception", description: "5 casques reçus avec la vitre brisée. Photo jointe.", status: "open", priority: "high", created_at: new Date(Date.now() - 1 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[2], profile: DEMO_USERS[0] },
  { id: "d2", ticket_number: "TKT-2026-02", user_id: "u5", order_id: "o4", subject: "Produit non conforme — taille incorrecte", description: "J'ai commandé 5 modèles 5kW mais reçu 3kW.", status: "in_progress", priority: "medium", created_at: new Date(Date.now() - 3 * 86400000).toISOString(), updated_at: new Date().toISOString(), order: DEMO_ORDERS[3], profile: DEMO_USERS[4] },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: "n1", title: "Nouvelle demande de devis", message: "DEV-2026-881234 reçue de Jean Koffi — Casques Bluetooth ANC ×200", type: "quote_request", recipient_type: "admin", is_read: false, created_at: new Date(Date.now() - 2 * 3600000).toISOString() },
  { id: "n2", title: "Paiement confirmé", message: "CMD-2026-1231 — Paiement virement reçu : 1 217 500 FCFA", type: "payment", recipient_type: "admin", is_read: false, created_at: new Date(Date.now() - 4 * 3600000).toISOString() },
  { id: "n3", title: "Litige ouvert", message: "Jean Koffi signale un colis endommagé sur CMD-2026-0871", type: "dispute", recipient_type: "admin", is_read: true, created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
  { id: "n4", title: "Expédition en transit", message: "CLA-AIR-71009 est en transit — ETA : dans 3 jours", type: "shipment", recipient_type: "admin", is_read: true, created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
  { id: "n5", title: "Devis expiré", message: "DEV-2026-441902 a expiré — relancer Paul Mbeki", type: "quote_expired", recipient_type: "admin", is_read: true, created_at: new Date(Date.now() - 2 * 86400000).toISOString() },
];
